version: '3.9'
services:
  redis-stack:
    image: redis/redis-stack:7.0.2-RC4
    volumes:
      - redis-stack-data:/bitnami/redis/data
    ports:
      - "8001:8001"
      - "6379:6379"
    networks:
      - redisnet

volumes:
  redis-stack-data:
    driver: local

networks:
  redisnet: { }
